#pragma once

#include <concepts>
#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <utility>

#include <entt/core/type_info.hpp>
#include <entt/signal/dispatcher.hpp>

#include <engine/engine_export.hpp>  // generated by generate_export_header()

#include <engine/core/CoreEvents.hpp>
#include <engine/core/FrameContext.hpp>
#include <engine/core/Subsystem.hpp>
#include <engine/core/Surface.hpp>
#include <engine/scene/Scene.hpp>

namespace enki {
class TaskScheduler;  // include <TaskScheduler.h> to use it
}

namespace engine {

[[nodiscard]] ENGINE_API std::string_view version() noexcept;

struct EngineConfig {
    std::string applicationName = "SRI";
    /// Where to render. Can also be set / changed later via Engine::SetSurface().
    NativeSurface surface{};
    /// Upper bound for a frame's delta time, so a breakpoint or a window drag
    /// doesn't produce a giant simulation step.
    double maxDeltaSeconds = 0.25;
    /// Task scheduler threads to create in addition to the main thread.
    /// 0 = one per hardware thread, minus the main thread.
    std::uint32_t taskThreads = 0;
};

/// The engine kernel: owns the subsystems, the active scene, the event
/// dispatcher and the task scheduler, and drives the frame loop.
///
/// Typical host usage:
///
///     engine::Engine engine{config};
///     engine.AddSubsystem<MyInputSubsystem>();
///     engine.AddSubsystem<MyRenderingSubsystem>();
///     engine.Initialize();
///     engine.Run();        // standalone game: blocks until RequestExit()
///     // or: call engine.Tick() from a timer   // editor: host owns the loop
///
/// Not movable: subsystems keep a pointer back to their Engine.
class Engine {
public:
    ENGINE_API explicit Engine(EngineConfig config = {});
    /// Calls Shutdown() if still initialized.
    ENGINE_API ~Engine();

    Engine(const Engine&) = delete;
    Engine& operator=(const Engine&) = delete;
    Engine(Engine&&) = delete;
    Engine& operator=(Engine&&) = delete;

    // --- Subsystems ------------------------------------------------------------
    // Subsystems are keyed by EnTT's type hash (derived from the type name), which,
    // unlike entt::type_index, is the same in the engine DLL and in the host.
    // Consequence: two types with the same fully qualified name (e.g. in anonymous
    // namespaces of different .cpp files) count as the same subsystem type.

    /// Registers a subsystem, only one per type. If the engine is already
    /// initialized the subsystem is initialized immediately.
    /// Returns nullptr (and logs why) if T is already registered or its late
    /// Initialize() failed.
    template <std::derived_from<Subsystem> T, typename... Args>
    T* AddSubsystem(Args&&... args) {
        return static_cast<T*>(RegisterSubsystem(entt::type_hash<T>::value(), entt::type_name<T>::value(),
                                                 std::make_unique<T>(std::forward<Args>(args)...)));
    }

    /// nullptr if no subsystem of exactly type T is registered.
    template <std::derived_from<Subsystem> T>
    [[nodiscard]] T* GetSubsystem() const noexcept {
        return static_cast<T*>(FindSubsystem(entt::type_hash<T>::value(), entt::type_name<T>::value()));
    }

    // --- Lifecycle -------------------------------------------------------------
    /// Initializes the task scheduler and all subsystems in registration order.
    /// If a subsystem fails, the ones already up are shut down again and this
    /// returns false.
    ENGINE_API bool Initialize();
    ENGINE_API void Shutdown();
    [[nodiscard]] ENGINE_API bool IsInitialized() const noexcept;

    /// Runs exactly one frame: all Update()s, then all Render()s.
    ENGINE_API void Tick();
    /// Initializes if needed, then Tick()s until RequestExit() is called.
    /// Something (e.g. a platform/window subsystem handling WM_QUIT) must call it.
    /// Returns false if initialization failed.
    ENGINE_API bool Run();
    ENGINE_API void RequestExit();
    [[nodiscard]] ENGINE_API bool IsExitRequested() const noexcept;

    /// While paused FrameContext::deltaSeconds is 0, but Update/Render still run.
    ENGINE_API void SetPaused(bool paused);
    [[nodiscard]] ENGINE_API bool IsPaused() const noexcept;

    // --- Output surface --------------------------------------------------------
    ENGINE_API void SetSurface(const NativeSurface& surface);
    ENGINE_API void ResizeSurface(std::uint32_t width, std::uint32_t height);
    [[nodiscard]] ENGINE_API const NativeSurface& GetSurface() const noexcept;

    // --- Shared state ----------------------------------------------------------
    [[nodiscard]] ENGINE_API const EngineConfig& GetConfig() const noexcept;
    /// The frame being processed (inside Tick) or the last completed one.
    [[nodiscard]] ENGINE_API const FrameContext& GetFrame() const noexcept;
    /// Engine-wide events. trigger() delivers immediately; enqueue()d events
    /// are delivered at the start of the next Tick(). Main thread only.
    [[nodiscard]] ENGINE_API entt::dispatcher& GetEvents() noexcept;
    [[nodiscard]] ENGINE_API Scene& GetScene() noexcept;
    /// enkiTS scheduler, running between Initialize() and Shutdown().
    /// The calling (main) thread takes part in WaitforTask().
    [[nodiscard]] ENGINE_API enki::TaskScheduler& GetTaskScheduler() noexcept;

    
private:
    ENGINE_API Subsystem* RegisterSubsystem(entt::id_type type, std::string_view typeName,
                                            std::unique_ptr<Subsystem> subsystem);
    [[nodiscard]] ENGINE_API Subsystem* FindSubsystem(entt::id_type type, std::string_view typeName) const noexcept;

    //pimpl
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace engine
