#pragma once

#include <memory>
#include <string_view>

#include <engine/engine_export.hpp>  // generated by generate_export_header()

namespace engine {

[[nodiscard]] ENGINE_API std::string_view version() noexcept;

class Engine {
public:
    ENGINE_API Engine();
    ENGINE_API ~Engine();

    Engine(const Engine&) = delete;
    Engine& operator=(const Engine&) = delete;
    ENGINE_API Engine(Engine&&) noexcept;
    ENGINE_API Engine& operator=(Engine&&) noexcept;
private:
    //pimpl
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace engine
